# Generated by Django 2.2.12 on 2020-04-28 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='delivery',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
